# 一、Scalar

## 标量
* 标量仅用于表达值的大小，也是零阶张量的一个例子。符号 x ∈ ℝ 表示标量 x 属于实数值数组“ ℝ ”。

* 在深度学习中我们比较关注以下几个数集，ℕ、ℤ 和ℚ。
* ℕ 表示正整数集（1,2,3，...）。 、
* ℤ 表示整数集，它包含了正值、负值和零值。 
* ℚ 表示可以由两个整数所构成的分数进行表达的有理数数集。
* Python 中内置了少数几种标量类型，如 int，float，complex，bytes，Unicode。
* 在 Python 库 NumPy 中，有 24 种新的基本数据类型来描述不同类型的标量。
* 采用np.isscalar(a)来判断a是否是标量

In [1]:
import numpy as np
np.isscalar(True)

True

In [2]:
np.isscalar([1, 3])

False

# 二、Vector

## 向量
* 向量是由多个单个数字组成的有序数组，也是一阶张量的一个例子。
* 向量是向量空间中的片段。向量空间则可以被认为是在特定长度（或维度）中所有可能存在的向量集合。
* 我们通常说的现实世界中的三维空间，在数学里可以用向量空间表达为 ℝ ^ 3。 

In [3]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
z = np.add(a, b)
c

[1, 2, 3, 4, 5, 6]

In [6]:
type(c)

list

In [4]:
z

array([5, 7, 9])

In [7]:
type(z)

numpy.ndarray

In [9]:
mul = np.cross(a, b)
mul
type(mul)

numpy.ndarray

# 三、Matrix

## 1、矩阵
* 矩阵是由数字构成的矩形阵列，是二阶张量的一个例子。
* 若 m 和 n 为正整数（ m，n ∈ N ），则 m × n 的矩阵中包含 m * n 个元素，由m 行和 n 列构成。
* 一般记为$A[a_{ij}]_{m * n}$

In [10]:
np.matrix([[1, 2], [3, 4]])

matrix([[1, 2],
        [3, 4]])

## 2、矩阵运算
* 矩阵可以与标量、向量或其他的矩阵进行相加。每一种加法都有一个精确的定义。

### 2.1、矩阵与矩阵的加法np.add(A,B)、A+B
* 两个矩阵对于位置的值相加得到相同规格的新矩阵

In [23]:
A = np.matrix([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
#A和B的形状必须一样

In [16]:
A

matrix([[1, 2],
        [3, 4]])

In [17]:
B

array([[5, 6],
       [7, 8]])

In [18]:
np.add(A, B)

matrix([[ 6,  8],
        [10, 12]])

### 2.2、矩阵与标量的加法
* 矩阵每个位置的值都与标量进行相加

In [26]:
A + 1

matrix([[2, 3],
        [4, 5]])

### 2.3、矩阵与标量的乘法
* 将给定矩阵中的各个元素都与给定的标量进行相乘

In [28]:
A * 2

matrix([[2, 4],
        [6, 8]])

### 2.4、矩阵之间的乘法A.dot(B)\np.matmul(A,B)
* 形状为 m x n 的矩阵 A 与形状为 n x p 的矩阵 B 相乘则会得到 形状为 m x p 的矩阵 C
* A的列与B的行相乘

In [29]:
A.dot(B)

matrix([[19, 22],
        [43, 50]])

In [30]:
np.matmul(A, B)

matrix([[19, 22],
        [43, 50]])

In [31]:
np.matmul(B, A)

matrix([[23, 34],
        [31, 46]])

### 2.5、矩阵的转置A.transpose\A.T

* 矩阵的转置可以使一个行向量变成一个列向量，或反方向操作亦成立作亦成立：
* A = [aij]m x n
* AT = [aji]n × m

In [33]:
A.transpose()

matrix([[1, 3],
        [2, 4]])

In [34]:
A.T

matrix([[1, 3],
        [2, 4]])

# Tensor

## 张量
* 笼统的来讲，张量包含了标量，向量，矩阵。有些时候，例如在物理及机器学习中，使用超过二阶的张量是非常必要的。