In [137]:
import numpy as np

In [138]:
x = np.arange(15)
X = x.reshape(3,5)

## 一、基本属性

### 1、ndim
查看数组的维度

In [139]:
X.ndim, x.ndim

(2, 1)

### 2、shape
返回一个tuple

In [140]:
X.shape, x.shape

((3, 5), (15,))

### 3、size

In [141]:
X.size, x.size

(15, 15)

## 二、numpy array的数据访问

## a、索引
### 1、x[n]
### 2、X[m][n]
表达：从X中的前m行中再取其中的前n行，很少用
## b、切片
### 3、x[m:n:d]
切片，从【m,)步长为d
### 4、X[m:n:d, x:y:b]
表达：X中的前m行中的前n列,步长分布为d、b

In [142]:
x[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [144]:
X[:2,2:4]

array([[2, 3],
       [7, 8]])

In [145]:
X[:2][:1]

array([[0, 1, 2, 3, 4]])

In [146]:
X[:, -1]

array([ 4,  9, 14])

In [147]:
X[0:2:3, :]

array([[0, 1, 2, 3, 4]])

## c、修改元素
### 赋值X[m,n] = y
### 复制
   * sub_x = X[m:n, x:y].copy().复制一个新的数组，其变化不会关联到原数组
   * sub_x = X[m:n, x:y]。复制一个新的数组，其变化会影响到原数组

## d、reshape（m,n）
* X = x.reshape(m,n), m*n=len(x)
* X = x.reshape(m,-1),自动计算n
* X = x.reshape(-1,n).自动计算m

## 三、合并操作
### 1、数组链接：np.concatenate([x, y, z···])
 * 两个矩阵列数要一样,维数也需要一样

In [148]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6, 7])
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [149]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6, 7])

In [150]:
np.concatenate([X, X])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [151]:
y

array([4, 5, 6, 7])

#### * 两个链接的数组维度和列数必须一致，否则不能进行concatenate

In [152]:
z = x.reshape(-1,3)
z

array([[1, 2, 3]])

In [153]:
np.concatenate([X,z])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### 2、行拼接np.vstack([x, y, z])
* 不要求x, y, z的维度一致，但需要列数一致

In [154]:
np.vstack([X, x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [216]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [215]:
np.vstack([X] * 4)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [155]:
y

array([4, 5, 6, 7])

### 3、列拼接np.hstack([])

In [156]:
X = np.arange(9).reshape(3,3)
x = np.arange(3).reshape(3,-1)
y = np.arange(3,6).reshape(3,-1)
x,y

(array([[0],
        [1],
        [2]]), array([[3],
        [4],
        [5]]))

In [218]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
np.hstack([X] * 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [217]:
Z = np.hstack([X, x, y])
Z

array([[0, 1, 2, 0, 3],
       [3, 4, 5, 1, 4],
       [6, 7, 8, 2, 5]])

## 四、分割操作
### 1、np.split(A, [m, n, p···]，axis=0,1)
* axis = 0,默认，按行分割
* axis = 1,按列分割

* 一维数组的分割

In [158]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
x1, x2, x3, x4 = np.split(a, [3,5,7])

In [160]:
x1

array([0, 1, 2])

In [161]:
x2

array([3, 4])

In [162]:
x4

array([7, 8, 9])

In [163]:
x1, x2 = np.split(a, [3])

In [164]:
x1

array([0, 1, 2])

In [165]:
x2

array([3, 4, 5, 6, 7, 8, 9])

* 矩阵分割——默认按行来分割（axis = 1或0）

In [166]:
A = np.arange(16).reshape(4,4)

In [167]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [168]:
A1, A2 = np.split(A, [2])
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [169]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* split参数axis默认为0，分割行,相当于vsplit

In [170]:
A1, A2, A3 = np.split(A, [1, 2])

In [171]:
A1

array([[0, 1, 2, 3]])

In [172]:
A2

array([[4, 5, 6, 7]])

In [173]:
A3

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* axis = 1则分割列,相当于hsplit

In [174]:
A1, A2, A3, A4 = np.split(A, [1, 2, 3], axis = 1)

In [175]:
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [176]:
A4

array([[ 3],
       [ 7],
       [11],
       [15]])

### 2、np.vsplit(A,[m,n,p···])

* np.vsplit():分割行，相当于axis = 0

In [177]:
upper, lower = np.vsplit(A, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [178]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 3、np.hsplit(A,[m,n,p···])

* np.hsplit():列分割，相当于axis = 1

In [179]:
left, right = np.hsplit(A, [2])

In [180]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [181]:
np.hsplit(A, [-1])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([[ 3],
        [ 7],
        [11],
        [15]])]

## 五、numpy.array中的运算

### 1、向量【列表】与常数相乘
* L*n：将向量L扩展n倍

In [182]:
L = [i for i in range(10)]

In [183]:
L * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 2、numpy.array与常数的universal function
* a * n:将array中的每个元素均乘n
* a + n
* a - n
* a / n
* a // n
* a % n
* a ** n

In [184]:
a = np.array([1,2,3,4])

In [185]:
a * 2

array([2, 4, 6, 8])

In [186]:
a + 2

array([3, 4, 5, 6])

In [187]:
a - 2

array([-1,  0,  1,  2])

In [188]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [189]:
a % 2

array([1, 0, 1, 0])

In [190]:
a // 2

array([0, 1, 1, 2])

In [191]:
a ** 2

array([ 1,  4,  9, 16])

### 3、函数计算
array：x的函数计算
* np.sin(x)
* np.cos(x)
* np.abs(x)
* np.exp(x),求e的x次方
* np.pow(n, x),求n的x次方，相当于n ** x
* np.log(x),
* np.log2(x)

In [192]:
a = np.arange(1, 10)

In [193]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [194]:
np.log2(a)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [195]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

### 4、矩阵运算
#### a、矩阵对于元素运算
要求A和B相同shape
* A * B
* A + B
* A - B
* A / B

In [196]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [197]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [198]:
A + B

array([[10, 11],
       [12, 13]])

In [199]:
A * B

array([[ 0, 10],
       [20, 30]])

In [200]:
A / B

array([[0. , 0.1],
       [0.2, 0.3]])

#### b、矩阵乘法A.dot(B)
C = A.dot(B)


若：A.shape: (m,p), B.shape:(p,n)


则C.shpae:(m,n)

矩阵乘法要求A的行数等于B的列数

A的行向量与B的列向量相乘再相加

C = np.full((2, 3),10)
C

In [202]:
D = np.arange(6).reshape(3,2)
D

array([[0, 1],
       [2, 3],
       [4, 5]])

In [203]:
D.dot(C)

array([[10, 10, 10],
       [50, 50, 50],
       [90, 90, 90]])

In [204]:
C.dot(D)

array([[60, 90],
       [60, 90]])

### 5、矩阵的转置A.T

In [205]:
D.T

array([[0, 2, 4],
       [1, 3, 5]])

### 6、向量与矩阵的元算

#### a、向量与矩阵相加

In [207]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [209]:
C

array([[10, 10, 10],
       [10, 10, 10]])

In [210]:
C + v

array([[11, 12, 13],
       [11, 12, 13]])

* 在数学中一个向量和矩阵相加没有意义，可以将向量堆叠为和需要相加的矩阵相同shape的矩阵，再相加

In [220]:
V = np.vstack([v] * C.shape[0])
V

array([[1, 2, 3],
       [1, 2, 3]])

* 以上vstack堆叠可以用np.tile（需要堆叠的向量，（纵向堆叠数量，横向堆叠次数））来实现

In [223]:
np.tile(v, (2, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [221]:
V + C

array([[11, 12, 13],
       [11, 12, 13]])

#### b、向量与矩阵的乘法
* v * A，得到的是v每个元素与A没行的对应元素相乘

In [227]:
v

array([1, 2, 3])

In [228]:
C

array([[10, 10, 10],
       [10, 10, 10]])

In [225]:
v * C

array([[10, 20, 30],
       [10, 20, 30]])

In [229]:
D

array([[0, 1],
       [2, 3],
       [4, 5]])

In [230]:
v.dot(D) 

array([16, 22])

### 7、矩阵的逆np.linalg.inv(A)
* 特征，A和A的逆相乘为单位矩阵（对角线为1）
* 只有方阵才有逆矩阵

In [231]:
A

array([[0, 1],
       [2, 3]])

In [233]:
inv_A = np.linalg.inv(A)

In [234]:
A.dot(inv_A)

array([[1., 0.],
       [0., 1.]])

### 8、伪逆矩阵
* 非方阵的伪逆矩阵

In [235]:
X = np.arange(10).reshape(5,-1)

In [236]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [239]:
pinv_X = np.linalg.pinv(X)

In [240]:
X.dot(pinv_X)

array([[ 6.00000000e-01,  4.00000000e-01,  2.00000000e-01,
        -8.66335515e-17, -2.00000000e-01],
       [ 4.00000000e-01,  3.00000000e-01,  2.00000000e-01,
         1.00000000e-01, -4.44089210e-16],
       [ 2.00000000e-01,  2.00000000e-01,  2.00000000e-01,
         2.00000000e-01,  2.00000000e-01],
       [ 1.22124533e-15,  1.00000000e-01,  2.00000000e-01,
         3.00000000e-01,  4.00000000e-01],
       [-2.00000000e-01,  0.00000000e+00,  2.00000000e-01,
         4.00000000e-01,  6.00000000e-01]])