# numpy.array的聚合操作

## 1、np.sum
* 比原生的sum（）效率高很多

## np.max() == L.max()
## np.min() == L.min()

In [2]:
import numpy as np
L = np.arange(100)

In [3]:
np.sum(L)

4950

In [4]:
sum(L)

4950

In [11]:
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 矩阵中的求元素总和，np.sum(X)

In [13]:
np.sum(X)

120

In [14]:
np.max(X)

15

### 矩阵中的按行求和，np.sum(X, axis =1)

In [9]:
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

In [15]:
np.max(X, axis = 1)

array([ 3,  7, 11, 15])

### 矩阵中的按列求和，np.sum(X, axis =0)

In [16]:
np.max(X, axis = 0)

array([12, 13, 14, 15])

In [12]:
np.sum(X, axis =0)

array([24, 28, 32, 36])

In [8]:
np.max(X)

15

## 2、np.prod（X）,求矩阵所有元素的乘积

In [17]:
np.prod(X)

0

In [18]:
np.prod(X + 1)

20922789888000

## 3、np.mean(X),平均值

In [23]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 求整个矩阵的平均值

In [19]:
np.mean(X)

7.5

### 按行求平均值

In [20]:
np.mean(X, axis = 1)

array([ 1.5,  5.5,  9.5, 13.5])

### 按列求平均值

In [21]:
np.mean(X, axis = 0)

array([6., 7., 8., 9.])

## 4、中位数np.median(X)
中位数比均值更能体现样本的特征

In [26]:
y = np.array([1, 2, 3, 10])

In [27]:
np.median(y)

2.5

### 5、百分位np.percentile(y, q=m)

m=0: 相当于min()


m=100:相当于max（）


m=50:相当于median

In [32]:
np.percentile(y, 50)

2.5

In [37]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(y, q = percent))


1.0
1.75
2.5
4.75
10.0


### 6、方差np.var(X)
* 每个样本值与全体样本值的平均数之差的平方值的平均数
* 研究方差即偏离程度有着重要意义
* 方差是衡量源数据和期望值相差的度量值

In [38]:
np.var(y)

12.5

$$var(y) = \sum_{i=1}^{len(y)}
{(y^{(i)} - \overline{y})^2}$$

In [44]:
sum = 0
var = 0
for i in y:
    sum += (i - np.mean(y)) ** 2
var = sum / len(y)
var

12.5

In [42]:
np.mean(y)

4.0

In [41]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.var(X, axis = 1)

array([1.25, 1.25, 1.25, 1.25])

### 7、标准差(均方差 )np.std(X)
* standard devition
* 用σ表示，标准差是方差的算术平方根
* 标准差能反映一个数据集的离散程度
* 平均数相同的两组数据，标准差未必相同

In [45]:
np.std(y)

3.5355339059327378

$$\sigma = \sqrt{\sum_{i=1}^{len(y)}
{(y^{(i)} - \overline{y})^2}}$$

In [46]:
np.sqrt(np.var(y))

3.5355339059327378