# numpy.array的arg索引运算

In [2]:
import numpy as np

## 一、索引
### 1、np.argmax(x)
求array_x中最大数的索引值

In [3]:
y = np.array([1, 2, 3, 4, 5, 6])

In [4]:
np.argmax(y)

5

In [5]:
y.argmax()

5

### 2、np.argmin(x)
求array_x中最下数的索引值

In [6]:
np.argmin(y)

0

In [7]:
y.argmin()

0

## 排序和使用索引

In [8]:
 x = np.arange(16)

### np.random.shuffle(x)对x进行乱序

In [9]:
np.random.shuffle(x)
x

array([ 0, 10, 15,  7, 13,  5, 11,  6,  3,  9, 14,  1,  4,  2,  8, 12])

### np.sort(X),对X进行排序

In [10]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
X = x.reshape(4,4)

In [12]:
np.random.shuffle(X)

In [13]:
X

array([[ 3,  9, 14,  1],
       [13,  5, 11,  6],
       [ 4,  2,  8, 12],
       [ 0, 10, 15,  7]])

In [14]:
Y = np.random.randint(10, size = (4,4))

In [15]:
Y

array([[4, 1, 6, 7],
       [5, 5, 5, 3],
       [9, 5, 6, 8],
       [4, 8, 2, 2]])

### np.argsort(x)排序后的索引位置

In [16]:
np.argsort(x)

array([12,  3,  9,  0,  8,  5,  7, 15, 10,  1, 13,  6, 11,  4,  2, 14])

In [17]:
np.argsort(Y)

array([[1, 0, 2, 3],
       [3, 0, 1, 2],
       [1, 2, 3, 0],
       [2, 3, 0, 1]])

### np.partition(x,n)
比n小的放在n之前，大的放在之后

In [18]:
np.partition(Y,2)

array([[1, 4, 6, 7],
       [3, 5, 5, 5],
       [5, 6, 8, 9],
       [2, 2, 4, 8]])

In [20]:
np.partition(x,5)

array([ 2,  0,  3,  1,  4,  5,  6,  9, 11, 13,  8, 12, 14, 10, 15,  7])

### np.argpartition(x,n)
返回partition（x，n）索引

In [21]:
np.argpartition(x,5)

array([ 9, 12,  0,  3,  8,  5,  7,  1,  6,  4, 10, 11,  2, 13, 14, 15])