In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## 1、高级切片
* X[n]
* X[m:n:d]
* X[list1, list2]:传入list变量，表达X的行下标列表、列下标列表，来寻找下标没有规律的值

In [2]:
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [3]:
X = x.reshape(4,4)

In [4]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

* X[list1, list2]：可以传入布尔类型的列表，对感兴趣的值true

In [5]:
col = [True, False, True, True]

In [7]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## 2、numpy.array的比较
* 返回比较条件是否成立的布尔数组
* X >\ <\ ==\ !=\>=\<=

In [11]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [13]:
x  + 3 < 9

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False])

## 3、条件统计函数
* np.sum(x<3)统计x中小于等于3的元素个数
* np.count_nonzero(x<=3),同上
* np.any(x=3)判断x中是否有元素等于3
* np.all(x > 0)判断x中所有元素都大于0
* 对于矩阵，可以传入axis = 0/1

In [15]:
np.sum(x <= 3)

4

In [17]:
np.count_nonzero(x <= 3)

4

In [20]:
np.any(x > 20)

False

In [21]:
np.all(x > 0)

False

In [22]:
np.sum(x % 2 == 0)

8